---
- hosts: all
  gather_facts: no
  tasks:
    - name: Running apt update
      yum: update_cache=yes
    - name: Installing required packages
      apt: name={{item}} state=present
      with_items:
       - python3

